
CREATE TABLE admins (
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`login` VARCHAR(254) NOT NULL,
`passwd` VARCHAR(254) NOT NULL
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS joueurs (
`id` BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY ,
`nom` VARCHAR(50) NOT NULL,
`prenom` VARCHAR(50) NOT NULL,
`naisssance` DATE NOT NULL,
`gsm` VARCHAR(8) NOT NULL,
`cin` VARCHAR(8) NOT NULL,
`adresse` TEXT NOT NULL,
`email` VARCHAR(100) NOT NULL,
`tirage` TINYINT(1) default NULL,
`date` DATE default NULL
) ENGINE = INNODB;
